### ISSUE TITLE
is there a way to show the tab search in the center of the screen just as Opera's Instant Search?

### ISSUE THREAD

**Issue by oquirozm** [janraasch/tab-ahead#111]
Hi again,

I would love to introduce some visual changes to tab-ahead so it looks and feels more like the Instant Search feature of Opera. What files or functions would be important to change to get it closer to that? Can I get there with changes in just the HTML and CSS or is there something else that's needed to be changed for this?

Thanks!

**Comment by janraasch** [comment]
Hi again :)

> I would love to introduce some visual changes to tab-ahead so it looks and feels more like the Instant Search feature of Opera. What files or functions would be important to change to get it closer to that?

Okay, so is your question really only about what you mentioned in the title of this issue or more broad? I'll try to answer both ways :)

# Question in the title

> Is there a way to show the tab search in the center of the screen?

Short answer is: No. Simply because this extension is currently implemented as a `Popup`. And as such Chrome renders the HTML **beneath** the `Popup`-Button. There might be other ways to do get this to work, but you'd have to look at the Chrome extensions API to find out. As it stands now, this is impossible :)

# Broader questions about changing HTML and CSS

> What files or functions would be important to change to get it closer to that? Can I get there with changes in just the HTML and CSS or is there something else that's needed to be changed for this?

First of all, I am not familiar with the *Instant Search*-Feature of Opera.

However, you should be fine editing

- HTML: https://github.com/janraasch/tab-ahead/blob/master/app/popup.html and
- CSS: https://github.com/janraasch/tab-ahead/blob/master/app/styles/main.css

There is some HTML-templating being done in JavaScript/Coffee

- https://github.com/janraasch/tab-ahead/blob/master/app/scripts/popup.coffee and
- https://github.com/janraasch/tab-ahead/blob/master/app/bower_components/flatstrap/assets/js/bootstrap-typeahead.js

but that is hopefully not to worry. Or rather, if you need to touch that, then you would really need to test behavior again. Esspecially, since the packaged `bootstrap-typeahead.js[https://github.com/janraasch/tab-ahead/blob/master/app/bower_components/flatstrap/assets/js/bootstrap-typeahead.js]` is no longer maintained.

I would suggest just playing around with the HTML and CSS to get a feel for it.

If you end up with some cool stuff, that you think would be of value to the rest of the world, send a pr and we can see, if we can merge it :)

Hope that helps.

Cheers,
Jan

**Comment by oquirozm** [comment]
Thanks a lot for your answer Jan! I hope I can do some work on my idea really soon but what you gave is enough for me to know where to start.

Omar
