### ISSUE TITLE
Allow search from omnibox

### ISSUE THREAD

**Issue by ashi009** [janraasch/tab-ahead#17]
It would be super cool to do the trick in omnibox instead of from the badge.

**Comment by janraasch** [comment]
Technically that might be possible, but from an UX perspective, it would seem strange to switch tabs and windows, after typing something into the *omnibox*, since usually you would expect to stay in the tab your in and have the address you just selected opened in the *current tab*.

**Comment by ashi009** [comment]
I'm not sure if it's strange. As this was implemented by Firefox's awesome
bar and I feel fine with it.

I'll make a preview in my fork later.

https://support.mozilla.org/en-US/kb/awesome-bar-find-your-bookmarks-history-and-tabs

**Comment by janraasch** [comment]
Yeah, sure. Always good to see it in action.

From the video, though, I can see that they only have **one** tab open. So when they type something and hit enter whatever webpage they selected is opened in the **same** tab. It does not seem like they switch context/tabs.

**Comment by shakeelmohamed** [comment]
+1 for this.

Valid use case for me:

+ Have too many tabs open to understand which planet I'm on
+ Need to go to a specific site (ex: Gmail, Trello)
+ Don't want to open another tab if it's already open, because loading all the JS can take a long time
+ So I go `<insert shortcut here>` and get no results for `gmail`
+ I hit enter/return and nothing happens.

For that last step, I'd want to open a new tab in the current window. Maybe we can do an experiment by hardcoding some values to match against? So, if there's no results - also check some hardcoded array of values, similar to what happens w/ Alfred for OS X

**Comment by jeffreycahyono** [comment]
+1

**Comment by janraasch** [comment]
@ashi009, finally got around to trying this in FireFox. I quiet like it. Did you ever get around to building a prototype of this?

**Comment by janraasch** [comment]
It seems like the only way to do this in Chrome would be to a keyword to the Omnibox, see https://developer.chrome.com/extensions/omnibox. So e.g. a user would need to type `tab` **and then** the title or url. Seems like more work to me than having a shortcut available. What do you think?

**Comment by ashi009** [comment]
I tried but then found I am inadequate in read/write coffeescript.
So I wrote a simple one for my personal use. I'm using `to` as the keyword, feels quite good.

**Comment by janraasch** [comment]
Seems legit. Is your code available some where? Might be interesting for others who are watching this issue to check it out.

**Comment by ashi009** [comment]
It's not available online. The main reason is that the code is highly experimental, which satisfies my needs but hardly a good reference for other people.

**Comment by janraasch** [comment]
No action in more than half a year. I am closing this issue.
