### ISSUE TITLE
Privacy Policies, Data Collection

### ISSUE THREAD

**Issue by enterit** [janraasch/tab-ahead#223]
Could you please clarify privacy policies for Tab Ahead extension?
Does it collect or send any user data over internet?

**Comment by janraasch** [comment]
Hi @enterit, thank you very much for getting in touch. 

ℹ️ **There is no outbound communication at all.**

Theoretically, you can use it offline...

Where would you expect this information? 

Let me know if I should update the README or one of the store descriptions, please.

Also, let me know if you have any other questions as well 😄.

Kind regards and I hope you're having fun with »Tab Ahead«,
Jan

**Comment by enterit** [comment]
Thanks Jan! That's a great extension, I've been using it a lot! I use tons of tabs, and this helps me finding what I need instantly.

Perhaps description in Chrome store would be a good place, since people may not always make an extra step and get to GitHub.

**Comment by janraasch** [comment]
Hi @enterit.

> Perhaps description in Chrome store would be a good place, since people may not always make an extra step and get to GitHub.

That makes sense. I updated the descriptions on both the [FireFox Marketplace](https://addons.mozilla.org/en-US/firefox/addon/tab-ahead-firefox/) and [Chrome Web Store](https://chrome.google.com/webstore/detail/tab-ahead/naoajjeoiblmpegfelhkapanmmaaghmi).

*Note* that it will take some before the `Privacy`-paragraph shows up on the Chrome Web Store, since their review process takes a little longer...

> That's a great extension, I've been using it a lot! I use tons of tabs, and this helps me finding what I need instantly.

That's great. If you do have a few euros/dollars/etc. 😜  to spare, I would appreciate a monetary acknowledgment as well 😸.

You may support my work on this extension via PayPal https://www.paypal.com/paypalme/janraasch/ `one-time - pay what you want` or GitHub Sponsors https://github.com/sponsors/janraasch `recurring - fixed fee`.

Thank you again for bringing this to my attention, and have a great start into the work week 👋🏻 ,
Jan
